### ISSUE TITLE
Github, rss, and gplus buttons misplaced.

### ISSUE THREAD

**Issue by JPAdv-zz** [CS-Club-at-SJSU/CS-Club-Site-at-SJSU#15]
It appears that the social buttons are not being aligned with the navigation bar in webkit. However, in firefox, they appear to be in the right places. Could this be a css issue?

**Comment by eblume** [comment]
Thanks! To add some background to this - when I wrote the css for this site I was new to Twitter Bootstrap. I now know that there are a number of classes that can be used to modify the way the titlebar is layed out, but I didn't properly use them.

Add to that the fact that I actually changed some bootstrap files directly and it might be a bit hard to fix this.

**Comment by Lanzaa** [comment]
Oi, I wanted to comment before closing this...

JPAdv, could you comment on whether this fixed the issue you were seeing? I checked it only in chromium.

**Comment by JPAdv-zz** [comment]
Yes, I would like to confirm that the issue has been resolved. Thanks a lot!
