### ISSUE TITLE
Live site has the word "TAIL" at the end of <body>, bottom left

### ISSUE THREAD

**Issue by eblume** [CS-Club-at-SJSU/CS-Club-Site-at-SJSU#6]
Very odd - the live site has the literal string (printed string) "TAIL" at the very bottom-left corner of the page. In the DOM, it is a bare string right after the google analytics script block.

This does not get printed at all in my test site, and I can't find the string "TAIL" anywhere in the entire codebase.

Was there a problem in the deploy procedure? Or is one of the scripts mucking with the DOM - probably the google analytics code?

**Comment by Lanzaa** [comment]
<joke> Web pages are not supposed to have tails ? </joke>

I was testing the deploy stuff and wanted to make a change to the site that would be synced over, but didn't want to make a change to the repo.

**Comment by eblume** [comment]
Hah - ok, fair enough.
